name: TinkerSwift
options:
  minimumXcodeGenVersion: 2.38.0
settings:
  base:
    SWIFT_VERSION: 6.0
    PRODUCT_BUNDLE_IDENTIFIER: com.ahmed.tinkerswift
    GENERATE_INFOPLIST_FILE: YES
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0
    DEVELOPMENT_TEAM: ""
packages:
  STTextView:
    url: https://github.com/krzyzanowskim/STTextView
    from: 2.2.2
  STTextViewPluginNeon:
    url: https://github.com/krzyzanowskim/STTextView-Plugin-Neon
    branch: main
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: 2.6.4
targets:
  TinkerSwift:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: TinkerSwift
    dependencies:
      - package: STTextView
        product: STTextView
      - package: STTextViewPluginNeon
        product: STTextView-Plugin-Neon
      - sdk: libsqlite3.tbd
      - package: Sparkle
        product: Sparkle
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: TinkerSwift/AppIcon.icon
        ENABLE_HARDENED_RUNTIME: YES
        PRODUCT_NAME: TinkerSwift
        CODE_SIGN_STYLE: Automatic
  TinkerSwiftTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: TinkerSwiftTests
    dependencies:
      - target: TinkerSwift
        SUFeedURL: https://ahmedash95.github.io/tinkerswift/appcast.xml
        SUPublicEDKey: PLACEHOLDER_KEY
